// <auto-generated />
namespace Shop_Management_System.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class relationship : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(relationship));
        
        string IMigrationMetadata.Id
        {
            get { return "202404161229342_relationship"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
